AWSTemplateFormatVersion: 2010-09-09
Resources:
  awsdhentonEC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  awsdhentonEC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref awsdhentonEC2Role
  awsdhentonEC2RolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: awsdhentonEC2RolePolicies
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource:
              - 'arn:aws:s3:::com.awsdhenton.deploy-bucket'
              - 'arn:aws:s3:::com.awsdhenton.deploy-bucket/*'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
              - 'elasticloadbalancing:DescribeInstanceHealth'
              - 'elasticloadbalancing:DescribeLoadBalancerAttributes'
              - 'elasticloadbalancing:DescribeLoadBalancers'
              - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
              - 'autoscaling:Describe*'
              - 'autoscaling:UpdateAutoScalingGroup'
              - 'autoscaling:EnterStandby'
              - 'autoscaling:ExitStandby'
            Resource: '*'
      Roles:
        - !Ref awsdhentonEC2Role
Outputs:
    InstanceProfile:
        Description: The instance profile to assign to your EC2 instances
        Value: !Ref awsdhentonEC2InstanceProfile
        Export: 
          Name: !Sub "${AWS::StackName}-InstanceProfile"